examenParcial/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('productos/',include('productos.urls')),
    path('tiendas/',include('tiendas.urls')),
    path('gestionTienda/', include('gestionTienda.urls')),
    path('', include('gestionTienda.urls')),
]

gestionTienda/urls.py
from django.urls import path
from . import views
from .views import gestion_tiendas, gestion_productos, tienda_detalle

app_name = 'gestionTienda'

urlpatterns = [
    path('gestionTienda/', gestion_tiendas, name='gestion_tiendas'),
    path('gestionTienda/Productos/', gestion_productos, name='gestion_productos'),
    path('gestionTienda/Tienda/<int:tienda_id>/', tienda_detalle, name='tienda_detalle'),

]

productos/urls.py
from django.urls import path
from . import views

app_name = 'productos'
urlpatterns = [
    path('', views.index, name='index'),
    path('producto', views.producto, name='producto')
]

tiendas/urls.py
from django.urls import path
from . import views

app_name = 'tiendas'
urlpatterns = [
    path('', views.index, name='index'),
    path('tienda', views.tienda, name='tienda')
]

productos/models.py
from django.db import models
from tiendas.models import Tienda


class Producto(models.Model):
    descripcion = models.CharField(max_length=400, blank=True, null=True)
    codigo = models.CharField(max_length=5, blank=True, null=True)
    precioventa = models.DecimalField(max_digits=10, decimal_places=2)
    cantidad = models.IntegerField()
    tiendafk = models.ForeignKey(Tienda, on_delete=models.SET_NULL, null=True)

tiendas/models.py
from django.db import models
from django.contrib.auth.models import User


class Tienda(models.Model):
    direccion = models.CharField(max_length=255, blank=True, null=True)
    provincia = models.CharField(max_length=255, blank=True, null=True)
    region = models.CharField(max_length=255, blank=True, null=True)
    fechacreacion = models.DateField(auto_now_add=True)
    telefonocontacto = models.CharField(max_length=10, blank=True, null=True)

gestionTienda/views.py
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse
from tiendas.models import Tienda
from productos.models import Producto

def gestion_tiendas(request):
    tiendas = Tienda.objects.all()
    return render(request, 'gestionTienda/gestion_tienda.html', {'tiendas': tiendas})

def gestion_productos(request):
    productos = Producto.objects.all()
    return render(request, 'gestion_productos.html', {'productos': productos})

def tienda_detalle(request, tienda_id):
    tienda = get_object_or_404(Tienda, pk=tienda_id)
    productos = Producto.objects.filter(tienda=tienda)
    return render(request, 'tienda_detalle.html', {'tienda': tienda, 'productos': productos})

productos/views.py
from django.shortcuts import render
from django.http import HttpResponse


def index(request):
    return HttpResponse('Bienvenidos a PRODUCTOS')


def producto(request):
    return HttpResponse('Bienvenidos a PRODUCTOS')

tiendas/views.py
from django.shortcuts import render
from django.http import HttpResponse


def index(request):
    return HttpResponse('Bienvenidos a la TIENDA')


def tienda(request):
    return HttpResponse('Bienvenidos a la TIENDA')

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Título de tu Página</title>
    <style>
        body {
            margin: 0;
            padding: 0;
            font-family: Arial, sans-serif;
        }



        main {
            padding: 20px;
        }

        footer {
            background-color: #2c3e50;
            color: white;
            text-align: center;
            padding: 10px;
            position: fixed;
            bottom: 0;
            width: 100%;
        }

         nav ul {
            list-style: none;
            padding: 0;
            margin: 0;
            background-color: #333;
            overflow: hidden;
        }

        nav li {
            float: left;
        }

        nav a {
            display: block;
            color: white;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
        }
    </style>
</head>

<body>
    <header>
        <h1>  </h1>
    </header>

    <main>
        <nav>
        <ul>
            <li><a href="{% url 'gestionTienda:gestion_tiendas' %}">Tienda</a></li>
            <li><a href="{% url 'gestionTienda:gestion_productos' %}">Producto</a></li>
        </ul>
    </nav>

    </main>

    
</body>

</html>

templates/gestionTienda/gestion_tienda.html
{% extends 'base.html' %}

{% block title %}Gestión de Tienda{% endblock %}

{% block pageContent %}

   <h2>Panel de Navegación</h2>
    <nav>
        <ul>
            <li><a href="{% url 'gestionTienda:gestion_tiendas' %}">Tienda</a></li>
            <li><a href="{% url 'gestionTienda:gestion_productos' %}">Producto</a></li>
        </ul>
    </nav>

    <h3>Gestión de Tienda</h3>
    <p>Aquí va tu contenido específico para la gestión de tienda.</p>
{% endblock %}

templates/inicio.html
<!DOCTYPE html>
<html>
    <head>
        <title>Bienvenidos a Django</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    </head>
    <body>
        <h1>Ruta : app2/inicio</h1>
        <form method="post" action="{% url 'app2:ingresoUsuario' %}">
            {% csrf_token %}
            <div>
                <label>Ingrese su nombre</label>
                <input type="text" name="nombreUsuario">
            </div>
            <div>
                <label>Ingrese su apellido</label>
                <input type="text" name="apellidoUsuario">
            </div>
            <div>
                <button type="submit">Registrar</button>
            </div>
        </form>

        {% for informacionUsuario in lista_usuarios %}
            <div>
                <p>Nombre del usuario : {{ informacionUsuario.nombreEstudiante }}</p>
                <p>Apellido del usuario : {{ informacionUsuario.apellidoEstudiante }}</p>
                <a class="btn btn-success" href="{% url 'app2:mostrarDatos' informacionUsuario.id %}">Mostrar</a>
            </div>
            <br>
        {% endfor %}
    </body>
</html>

templates/productos.html
{% extends 'base.html' %}

{% load static %}

{% block pageContent %}
    <div class="container" style="height: 100vh; overflow: scroll;">
        <h1 class="mt-3 mb-3">Productos</h1>
        <br>
        <div class="row mx-0">
            <div class="col-2">
                <div class="row mx-0">
                    <a class="btn btn-success text-white" data-bs-toggle="modal" data-bs-target="#nuevoProducto">Nuevo <i class="fa-solid fa-store"></i></a>
                </div>
            </div>
        </div>
        <br>
        <div>
            <table class="table table-bordered table-hover" id="usersTable" style="font-size: 12px;">
                <thead class="table-dark">
                    <th scope="col">Nombre</th>
                    <th scope="col">Codigo</th>
                    <th scope="col">Precio</th>
                    <th scope="col">Cantidad</th>
                    <th scope="col">Peso</th>
                    <th scope="col">Almacen</th>
                    <th scope="col">Editar</th>
                    <th scope="col">Eliminar</th>
                </thead>
                <tbody>
                    {% for productoInfo in productosTotales %}
                    <tr>
                        <td>{{ productoInfo.nombreProducto }}</td>
                        <td>{{ productoInfo.codigoProducto }}</td>
                        <td>{{ productoInfo.precioProducto }}</td>
                        <td>{{ productoInfo.cantidadProducto }}</td>
                        <td>{{ productoInfo.pesoProducto }}</td>
                        <td>{{ productoInfo.almacenProducto.nombreAlmacen }}</td>
                        <td></td>
                        <td></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

{% block modalContent %}
    <!-- Nuevo producto modal window -->
    <div class="modal fade" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" role="dialog" id="nuevoProducto">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <form action="{% url 'app3:productos' %}" method="post">
                    {% csrf_token %}
                    <div class="modal-header">
                        <h5 class="modal-title">Nuevo producto</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <div class="row mb-3 mt-3">
                            <div class="col-6">
                                <label>Nombre</label>
                                <input type="text" class="form-control" name="nombreProducto" id="nombreProducto" required>
                            </div>
                            <div class="col-6">
                                <label>Codigo</label>
                                <input type="text" class="form-control" name="codigoProducto" id="codigoProducto" required>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-6">
                                <label>Precio</label>
                                <input type="text" class="form-control" name="precioProducto" id="precioProducto" required>
                            </div>
                            <div class="col-6">
                                <label>Cantidad</label>
                                <input type="text" class="form-control" name="cantidadProducto" id="cantidadProducto" required>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-6">
                                <label>Peso</label>
                                <input type="text" class="form-control" name="pesoProducto" id="pesoProducto" required>
                            </div>
                            <div class="col-6">
                                <label>Almacen</label>
                                <select class="form-select" name="almacenProducto" required>
                                    <option value=""></option>
                                    {% for almacenInfo in almacenesTotales %}
                                    <option value="{{ almacenInfo.id }}">{{ almacenInfo.nombreAlmacen }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                        <button type="submit" class="btn btn-primary">Crear</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/react.html
{% extends 'base.html' %}

{% load static %}

{% block extraFiles %}
    <script src="https://unpkg.com/react@18/umd/react.development.js" crossorigin></script>
    <script src="https://unpkg.com/react-dom@18/umd/react-dom.development.js" crossorigin></script>
    <script src="https://unpkg.com/babel-standalone@6/babel.min.js"></script>
{% endblock %}

{% block pageContent %}
    <div id="app" class="container" style="height: 100vh; overflow: scroll;">
    </div>

    <script type="text/babel">
        function Iterar()
        {
            const [state,setState] = React.useState({
                usuarios:['Alexander','Javier'],
                nuevoUsuario:''
            })

            function actualizarNuevoUsuario(event)
            {
                setState({
                    usuarios:state.usuarios,
                    nuevoUsuario: event.target.value
                })
            }

            function agregarUsuario()
            {
                setState({
                    usuarios:[...state.usuarios,state.nuevoUsuario],
                    nuevoUsuario:'',
                })
            }


            return(
                <div className='row'>
                    {
                        state.usuarios.map((usuario,index) => {
                            return(<App key={index} nombre={usuario} />);
                        })  
                    }
                    <div className='row'>
                        <div className='col-4'>
                            <input className='form-control' value={state.nuevoUsuario} onChange={actualizarNuevoUsuario}/>
                        </div>
                        <div className='col-2'>
                            <button className='btn btn-primary' onClick={agregarUsuario}>Agregar</button>
                        </div>
                    </div>
                </div>
            );
        }

        function App(props)
        {
            return(
                <h1>Bienvenido {props.nombre}</h1>
            );
        }
        const root = ReactDOM.createRoot(document.querySelector('#app'))
        root.render(<Iterar />)
    </script>
{% endblock %}